service: intro_to_graphql

plugins:
  - serverless-webpack
  - serverless-plugin-common-excludes
  - serverless-offline

package:
  individually: true

custom:
  webpackIncludeModules: true
  serverless-offline:
    port: 3000

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2
  memorySize: 128
  timeout: 5
  environment:
    REACT_APP_GRAPHQL_ENDPOINT: http://localhost:3000/graphql

functions:
  graphql:
    handler: handlers/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
  graphiql:
    handler: handlers/graphiql.handler
    events:
      - http:
          path: graphiql
          method: get
          cors: true
  playground:
    handler: handlers/playground.handler
    events:
      - http:
          path: playground
          method: get
          cors: true
  testdb:
    handler: handlers/testdb.handler
    events:
      - http:
          path: testdb
          method: get
  preparedb:
    handler: handlers/preparedb.handler
    events:
      - http:
          path: preparedb
          method: get
